; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{6AF0D7FC-FAC3-4388-85E6-7B61AE10533D}
AppName=Gestionare clienti v 6.0
AppVersion=6
;AppVerName=Gestionare clienti v 6.0 6
AppPublisher=Secret Data, Inc.
AppPublisherURL=https://www.example.com/
AppSupportURL=https://www.example.com/
AppUpdatesURL=https://www.example.com/
DefaultDirName={autopf}\Gestionare clienti v 6.0
UninstallDisplayIcon={app}\Gestiune_clienti_sqlite_v6.0.exe
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
ChangesAssociations=yes
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputDir=D:\upgrade_gestionare_clienti_anaf\Output
OutputBaseFilename=gestionare v6
SetupIconFile=D:\upgrade_gestionare_clienti_anaf\icon.ico
SolidCompression=yes
WizardStyle=modern dark polar

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "D:\upgrade_gestionare_clienti_anaf\dist\Gestiune_clienti_sqlite_v6.0\Gestiune_clienti_sqlite_v6.0.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\upgrade_gestionare_clienti_anaf\dist\Gestiune_clienti_sqlite_v6.0\_internal\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "D:\upgrade_gestionare_clienti_anaf\baza_date.db"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\upgrade_gestionare_clienti_anaf\icon.ico"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\upgrade_gestionare_clienti_anaf\icon.png"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\upgrade_gestionare_clienti_anaf\mapping_model_amef.xlsx"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\upgrade_gestionare_clienti_anaf\mapping_tehnician.xlsx"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
Root: HKA; Subkey: "Software\Classes\.exe\OpenWithProgids"; ValueType: string; ValueName: "Gestionareclientiv6.0File.exe"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\Gestionareclientiv6.0File.exe"; ValueType: string; ValueName: ""; ValueData: "Gestionare clienti v 6.0 File"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\Gestionareclientiv6.0File.exe\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\Gestiune_clienti_sqlite_v6.0.exe,0"
Root: HKA; Subkey: "Software\Classes\Gestionareclientiv6.0File.exe\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\Gestiune_clienti_sqlite_v6.0.exe"" ""%1"""

[Icons]
Name: "{autoprograms}\Gestionare clienti v 6.0"; Filename: "{app}\Gestiune_clienti_sqlite_v6.0.exe"
Name: "{autodesktop}\Gestionare clienti v 6.0"; Filename: "{app}\Gestiune_clienti_sqlite_v6.0.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\Gestiune_clienti_sqlite_v6.0.exe"; Description: "{cm:LaunchProgram,Gestionare clienti v 6.0}"; Flags: nowait postinstall skipifsilent

